# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def pods
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'Alamofire', '~> 5.4'
end

target 'TestAssignment' do
  pods
end


target 'TestAssignmentTests' do
  inherit! :search_paths
  pods
  end
